#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
source "$ROOT/tests/workflow-modes/lib.sh"

SELECTOR="$ROOT/skills/selecting-workflow-mode/SKILL.md"
MATRIX="$ROOT/skills/selecting-workflow-mode/references/risk-matrix.md"
BOOTSTRAP="$ROOT/skills/using-superpowers/SKILL.md"
CODEX_TOOLS="$ROOT/skills/using-superpowers/references/codex-tools.md"

assert_file "$SELECTOR" "selector skill exists"
assert_file "$MATRIX" "risk matrix exists"

if [[ -f "$SELECTOR" ]]; then
  assert_contains "$SELECTOR" "Active workflow mode:" "selector defines active mode state"
  assert_contains "$SELECTOR" "Mode: <lean|standard|strict> — <one-sentence reason>." "selector defines one-line declaration"
  assert_contains "$SELECTOR" "Never demote automatically" "selector forbids automatic demotion"
  assert_contains "$SELECTOR" 'Promoting to strict — inspection found <source> defines <field> consumed by <consumer> as part of <strict surface>; <change> would <consequence>.' "selector defines canonical evidence-backed promotion"
  assert_contains "$SELECTOR" "pause before the first mutation" "selector requires a post-inspection pause before mutation"
  assert_contains "$SELECTOR" "Do not use shell chaining, pipelines, redirections, command substitution" "selector requires auditable read-only inspection"
  assert_contains "$SELECTOR" "When dedicated Read, Glob, or Grep tools are available, use only those" "selector prefers structurally read-only inspection tools"
  assert_contains "$SELECTOR" "Do not probe optional instruction files" "selector avoids nonexistent optional instruction probes"
  assert_contains "$SELECTOR" "read both the defining file and an actual consuming file" "selector requires direct source and consumer evidence"
  assert_contains "$SELECTOR" "Do not treat a source comment as proof of a consumer" "selector rejects inferred consumer evidence"
  assert_contains "$SELECTOR" "Promotion evidence for each named source and consumer must come from that file's own literal exact-path read." "selector requires literal exact-path promotion evidence"
  assert_contains "$SELECTOR" "A wildcard or glob read may discover candidate paths, but it cannot establish consumer identity or count as source or consumer proof." "selector limits wildcard reads to discovery"
  assert_contains "$SELECTOR" "Do not name a file in the promotion line unless that exact path was read literally and successfully." "selector forbids fabricated promotion paths"
  assert_contains "$SELECTOR" 'Do not output another `Mode:` line' "selector forbids a second mode declaration during promotion"
  assert_contains "$SELECTOR" 'If `User override` is `lean` or `standard`, warn without promoting and keep that explicitly chosen mode active.' "selector preserves explicit non-strict overrides"
  assert_contains "$SELECTOR" 'If the active mode is already `strict`, whether selected automatically or explicitly, do not output a promotion.' "selector forbids duplicate strict promotion"
  assert_contains "$SELECTOR" 'Canonical promotion requires both `User override: none` and an active mode of `lean` or `standard`.' "selector limits automatic promotion to non-strict automatic modes"
  assert_contains "$SELECTOR" "Explicit user mode instructions are authoritative" "selector honors overrides"
  assert_contains "$SELECTOR" "A materially different requested outcome starts a new task." "selector defines task continuity"
  assert_contains "$SELECTOR" "Re-entry applies only when the selector is invoked again within the same ongoing task" "selector limits re-entry to the ongoing task"
  assert_contains "$SELECTOR" "A prior active mode or user override does not make a materially different requested outcome a re-entry." "selector resets routing at a new-task boundary"
  assert_contains "$SELECTOR" 'load the risk matrix, classify the new task, and emit one fresh `Mode:` declaration' "selector reruns task entry for a materially different outcome"
  assert_contains "$SELECTOR" "If an active workflow mode is already present for that ongoing task, this is" "selector distinguishes active-mode re-entry"
  assert_contains "$SELECTOR" 'Do not output a new `Mode:` declaration on re-entry.' "selector forbids a second declaration on re-entry"
  assert_contains "$SELECTOR" "Apply the override and promotion rules below to the existing state." "selector routes re-entry through existing state"
  assert_contains "$SELECTOR" 'In `standard`, after project inspection and before the first mutation, output a short inline design and execution outline in a visible inline message.' "selector owns the standard inline outline"
  assert_contains "$SELECTOR" "Continue without an approval pause unless a missing decision would materially alter the result." "selector keeps standard execution continuous"
  assert_contains "$SELECTOR" 'If the task request itself contains a concrete strict trigger under an explicit `lean` or `standard` override, output the warning immediately after the `Mode:` line and before project inspection.' "selector warns immediately when request text conflicts with a non-strict override"
  assert_contains "$SELECTOR" 'Risk routing and active-mode readiness are separate obligations, not mutually exclusive branches.' "selector separates risk routing from mode readiness"
  assert_contains "$SELECTOR" 'Explicit `standard` plus strict evidence: warn, retain `standard`, then complete the standard inline outline before mutation.' "selector combines explicit standard warning with standard readiness"
  assert_not_matches "$SELECTOR" 'exactly one checkpoint branch' "selector does not make warning and standard outline mutually exclusive"
  assert_contains "$SELECTOR" 'A safe discovery command may be standalone `rg --files` or standalone `rg -n`' "selector permits closed read-only rg discovery"
  assert_contains "$SELECTOR" 'The only permitted discovery pipeline is one allowed `rg` discovery command followed by one output-limiting `sed -n` command.' "selector closes the read-only discovery pipeline grammar"
  assert_contains "$SELECTOR" 'For `rg --files`, allow only repeated `-g <glob>` or `--glob <glob>` pairs and project path operands, in any order.' "selector allowlists rg files discovery tokens in parser order"
  assert_contains "$SELECTOR" 'For `rg -n` or `rg --line-number`, allow only repeated `-g <glob>` or `--glob <glob>` pairs, `--hidden`, `--no-heading`, `--color=never`, and positionals; the allowlisted flags may appear anywhere.' "selector allowlists rg content discovery tokens in parser order"
  assert_contains "$SELECTOR" 'The first non-option positional must be a non-hyphen search pattern; every later positional is a project path operand.' "selector closes rg content discovery operands"
  assert_contains "$SELECTOR" "The output limiter must be exactly \`sed -n '<positive-start>[,<positive-end>]p'\`; no other \`sed\` flags, scripts, or operands are allowed." "selector closes discovery output limiter"
  assert_contains "$SELECTOR" 'All other `rg` flags are forbidden here, including command-bearing `--pre` and `--pre-glob`.' "selector forbids command-bearing rg flags"
  assert_contains "$SELECTOR" 'Shell parameter expansion (`$name` or `${...}`), backticks, and unquoted brace, tilde, or glob expansion are forbidden.' "selector forbids shell expansion in discovery"
  assert_contains "$SELECTOR" 'Regex or glob metacharacters in an `rg` search pattern or `-g`/`--glob` argument must be inside one single-quoted token.' "selector requires quoted discovery metacharacters"
  assert_contains "$SELECTOR" 'Discovery never counts as strict-promotion proof.' "selector separates discovery from promotion proof"
  assert_contains "$SELECTOR" 'For strict-promotion proof, read each exact source and consumer path with its own standalone `cat` or `sed -n` command.' "selector preserves literal exact-path proof"
  assert_not_matches "$SELECTOR" '\b(gpt|claude|gemini|opus|sonnet|fable)\b' "selector has no model allowlist"
fi

if [[ -f "$MATRIX" ]]; then
  assert_contains "$MATRIX" 'Default to `standard`' "matrix defines ambiguous default"
  assert_contains "$MATRIX" 'A schema or consumer rename with unknown blast radius starts in `standard`' "matrix keeps unknown rename impact standard until inspection"
  assert_contains "$MATRIX" "Authentication, authorization, or secrets" "matrix defines security trigger"
  assert_contains "$MATRIX" "Production data or data migration" "matrix defines data trigger"
  assert_contains "$MATRIX" 'An explicit `lean` or `standard` choice remains active when later inspection reveals a strict trigger.' "matrix preserves explicit non-strict override"
  assert_contains "$MATRIX" "Warn about the risk without auto-promoting." "matrix warns instead of promoting explicit non-strict mode"
  assert_contains "$MATRIX" 'An explicit `strict` choice remains strict.' "matrix preserves explicit strict mode"
  assert_not_matches "$MATRIX" '\b(gpt|claude|gemini|opus|sonnet|fable)\b' "matrix has no model allowlist"
fi

assert_contains "$BOOTSTRAP" "selecting-workflow-mode" "bootstrap invokes selector first"
assert_contains "$BOOTSTRAP" 'On platforms with native skill loading, if they are not already loaded, invoke `selecting-workflow-mode`; it loads its risk matrix before classifying.' "bootstrap defines platform-neutral selector loading"
assert_contains "$BOOTSTRAP" 'read this skill alone, then read `selecting-workflow-mode` alone, then read its risk matrix alone' "bootstrap defines standalone Codex read sequence"
assert_contains "$BOOTSTRAP" 'skills/selecting-workflow-mode/references/risk-matrix.md' "bootstrap gives Codex the exact literal matrix path"
assert_contains "$BOOTSTRAP" "Do not combine those reads with each other or with project inspection" "bootstrap forbids compound Codex bootstrap reads"
assert_contains "$BOOTSTRAP" "before any project command or other tool" "bootstrap orders declaration before task tools"
assert_contains "$BOOTSTRAP" "Do not invoke a general process skill before a mode is active." "bootstrap enforces routing order"
assert_contains "$BOOTSTRAP" "Explicitly requested skills still run" "bootstrap preserves explicit skill requests"
assert_contains "$BOOTSTRAP" "Domain and artifact skills remain available in every mode." "bootstrap preserves domain skills"
assert_contains "$BOOTSTRAP" '## Before the first mutation' "bootstrap exposes the pre-mutation checkpoint at high salience"
assert_contains "$BOOTSTRAP" 'If the request itself exposes a concrete strict trigger under an explicit `lean` or `standard` override, warn immediately after the `Mode:` line and before project inspection.' "bootstrap orders request-triggered override warnings"
assert_contains "$BOOTSTRAP" 'Automatic `lean` or `standard` plus strict evidence: output the selector' "bootstrap requires automatic strict promotion"
assert_contains "$BOOTSTRAP" 'Risk routing does not replace active-mode readiness.' "bootstrap separates risk routing from readiness"
assert_contains "$BOOTSTRAP" 'If `standard` remains active after routing, including an explicit `standard` override with strict evidence, output a short visible inline outline covering approach, affected files or components, and verification.' "bootstrap requires standard outline after override warning"
assert_contains "$BOOTSTRAP" '`strict` is active, invoke every relevant skill before any further response or action.' "bootstrap restores strict before-action skill invocation"
assert_contains "$BOOTSTRAP" "response or action." "bootstrap restores strict response-and-action coverage"
assert_contains "$BOOTSTRAP" "Even a 1% chance that a skill applies means it is relevant." "bootstrap restores strict relevance floor"
assert_contains "$BOOTSTRAP" "Process skills run before implementation skills." "bootstrap restores strict skill priority"
assert_contains "$BOOTSTRAP" '"Let me explore first"' "bootstrap restores strict exploration rationalization guard"
assert_contains "$BOOTSTRAP" '"This is just a simple question"' "bootstrap restores strict simplicity rationalization guard"
assert_contains "$BOOTSTRAP" '"I can check files quickly"' "bootstrap restores strict quick-inspection rationalization guard"
assert_contains "$BOOTSTRAP" '"The skill is overkill"' "bootstrap restores strict overkill rationalization guard"
assert_contains "$BOOTSTRAP" '"This feels productive"' "bootstrap restores strict productivity rationalization guard"
assert_contains "$CODEX_TOOLS" 'using-superpowers/SKILL.md` by itself' "Codex guide starts with standalone bootstrap read"
assert_contains "$CODEX_TOOLS" 'selecting-workflow-mode/SKILL.md` by itself' "Codex guide reads selector separately"
assert_contains "$CODEX_TOOLS" 'risk-matrix.md` by itself' "Codex guide reads matrix separately"
assert_contains "$CODEX_TOOLS" 'Do not use `&&`, `||`, pipes, redirections' "Codex guide bans compound bootstrap commands"
finish
