#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
source "$ROOT/tests/workflow-modes/lib.sh"

assert_count() {
  local path="$1" pattern="$2" expected="$3" label="$4" actual
  actual="$(rg -c -- "$pattern" "$path" || true)"
  [[ "$actual" == "$expected" ]] && pass "$label" || fail "$label"
}

DEBUG="$ROOT/skills/systematic-debugging/SKILL.md"
VERIFY="$ROOT/skills/verification-before-completion/SKILL.md"
EVIDENCE_VALIDATOR="$ROOT/tests/workflow-modes/assert-task4-evidence.sh"

[[ -x "$EVIDENCE_VALIDATOR" ]] \
  && pass "Task 4 durable evidence validator is executable" \
  || fail "Task 4 durable evidence validator is executable"
assert_contains "$EVIDENCE_VALIDATOR" '"masked exit status" "npm test; echo $?"' "validator self-tests masked exit rejection"
assert_contains "$EVIDENCE_VALIDATOR" '"pipe without spaces" "npm test|cat"' "validator self-tests compact pipeline rejection"
assert_contains "$EVIDENCE_VALIDATOR" '"newline trailing command"' "validator self-tests multiline command rejection"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects general fix plus special-case decoy edit" "validator self-tests decoy edit rejection"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects expected hunk plus harmful mixed diff" "validator self-tests mixed diff rejection"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects duplicate correlated results" "validator self-tests result cardinality"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects one pre-call plus one post-call result" "validator self-tests total result cardinality"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects duplicate matching calls" "validator self-tests call cardinality"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects mixed PASS and FAIL output" "validator self-tests mixed result rejection"
assert_contains "$EVIDENCE_VALIDATOR" '"count-before-key failing form"' "validator self-tests count-before failure markers"
assert_contains "$EVIDENCE_VALIDATOR" '"key-before-count singular error with leading zero"' "validator self-tests key-before leading-zero failure markers"
assert_contains "$EVIDENCE_VALIDATOR" '"explicit zero counters"' "validator self-tests explicit zero counters"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects extra strict status lines" "validator self-tests exact strict status"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects extra files in strict unscoped diff" "validator self-tests unscoped strict diff extras"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects broad claims from focused evidence" "validator self-tests focused-claim scope"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects missing strict plan assertion" "validator self-tests strict requirement enumeration"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects labels that appear only before final evidence" "validator self-tests early-only labels"
assert_contains "$EVIDENCE_VALIDATOR" "negative self-test rejects PASS followed by contradictory FAIL" "validator self-tests contradictory final labels"
assert_contains "$EVIDENCE_VALIDATOR" "uses the exact standalone Bash allowlist" "validator enforces per-scenario command allowlists"
assert_contains "$EVIDENCE_VALIDATOR" "has exactly one total later result per call and no orphan results" "validator enforces global call/result integrity"
assert_contains "$EVIDENCE_VALIDATOR" "has exactly the expected normalized status lines" "validator enforces strict workspace status"
assert_contains "$EVIDENCE_VALIDATOR" 'diff_command="git diff"' "validator enforces unscoped strict diff"
assert_contains "$EVIDENCE_VALIDATOR" "diff contains only the exact expected hunks" "validator enforces exact diff integrity"
assert_contains "$EVIDENCE_VALIDATOR" "in the final response" "validator enforces final-response labels"
assert_contains "$EVIDENCE_VALIDATOR" "PHASES: 1,2,3,4" "validator enforces strict phase label"
assert_contains "$EVIDENCE_VALIDATOR" "DEPTH: STRICT_FULL_TDD" "validator enforces strict depth label"

for skill in "$DEBUG" "$VERIFY"; do
  assert_contains "$skill" "<WORKFLOW-MODE-DEPTH>" "$(basename "$(dirname "$skill")") defines mode depth"
  assert_count "$skill" '^<WORKFLOW-MODE-DEPTH>$' 1 "$(basename "$(dirname "$skill")") has one opening mode-depth contract"
  assert_count "$skill" '^</WORKFLOW-MODE-DEPTH>$' 1 "$(basename "$(dirname "$skill")") has one closing mode-depth contract"
done

assert_contains "$DEBUG" "Root-cause evidence is mandatory in every mode." "debugging retains root-cause floor"
assert_contains "$DEBUG" '- `lean`: reproduce the symptom, then identify an evidence-backed root cause' "debugging lean requires symptom reproduction"
assert_contains "$DEBUG" "before making any fix. Make the smallest fix, run the regression check, and" "debugging requires root-cause evidence before a lean fix"
assert_contains "$DEBUG" "inspect the diff. If evidence does not identify the cause directly, escalate" "debugging lean escalates when evidence is insufficient"
assert_contains "$DEBUG" "to standard debugging depth without changing the active workflow mode." "debugging depth escalation preserves active mode"
assert_contains "$DEBUG" '- `standard`: use an explicit hypothesis-and-test loop, then implement and' "debugging defines standard hypothesis loop"
assert_contains "$DEBUG" '- `strict`: follow all four phases and every existing gate unchanged.' "debugging preserves strict path"
assert_contains "$DEBUG" '- no active mode: invoke `selecting-workflow-mode`.' "debugging selects when mode is absent"
assert_contains "$DEBUG" "Do not reclassify the task here." "debugging does not reclassify"
assert_contains "$DEBUG" "A debugging-depth escalation does not change the active workflow mode." "debugging separates depth from workflow mode"
assert_contains "$DEBUG" "only that selector may promote the active workflow mode." "debugging reserves risk promotion for selector"
assert_contains "$DEBUG" "Do not use mode selection to justify guessing or symptom patching." "debugging forbids weakened evidence"
assert_contains "$DEBUG" "Run reproduction and regression checks as standalone commands so each tool" "debugging preserves raw command status"
assert_contains "$DEBUG" "result exposes its actual exit status." "debugging forbids masked regression status"
assert_contains "$DEBUG" 'Appending status-printing or masking syntax such as `; echo`, `|| true`,' "debugging names invalid masked evidence"
assert_contains "$DEBUG" "pipelines, or fallback commands invalidates that evidence; rerun the check" "debugging rejects masked command results"
assert_contains "$DEBUG" "standalone." "debugging requires standalone rerun"
assert_contains "$DEBUG" 'After editing, run `git diff` as a standalone command and inspect its result.' "debugging requires observable post-fix diff"
assert_contains "$DEBUG" "In strict mode, you MUST complete each phase before proceeding to the next." "debugging keeps strict phase sequencing"
assert_contains "$DEBUG" 'In standard and lean, the depth contract above determines the required path.' "debugging uses active-mode depth outside strict"
assert_contains "$DEBUG" "In strict mode, if you haven't completed Phase 1, you cannot propose fixes." "debugging keeps complete Phase 1 gate in strict"
assert_contains "$DEBUG" "In standard and lean, you cannot propose a fix until you have reproduced the" "debugging scopes no-fix gate outside strict"
assert_contains "$DEBUG" "symptom and identified an evidence-backed root cause." "debugging keeps invariant pre-fix evidence"
assert_contains "$DEBUG" 'In strict mode, this is mandatory and uses `test-driven-development`.' "debugging preserves strict TDD"
assert_contains "$DEBUG" "In lean mode, a reproducible regression check may be written before or" "debugging allows lean regression timing"
assert_contains "$DEBUG" "after the fix, but it must demonstrate the corrected behavior." "debugging lean still proves corrected behavior"
assert_not_matches "$DEBUG" 'reproduce or inspect|promote to standard' "debugging removes ambiguous lean shortcuts"

assert_contains "$VERIFY" "The evidence rule is identical in every mode." "verification iron law is invariant"
assert_contains "$VERIFY" '- `lean`: run the most relevant test or check and inspect the resulting diff.' "verification defines lean breadth"
assert_contains "$VERIFY" '- `standard`: run relevant tests, static checks, and integrated verification.' "verification defines standard breadth"
assert_contains "$VERIFY" '- `strict`: run the complete suite and verify requirements against the written' "verification preserves strict breadth"
assert_contains "$VERIFY" '- no active mode: invoke `selecting-workflow-mode`.' "verification selects when mode is absent"
assert_contains "$VERIFY" "Do not reclassify the task here." "verification does not reclassify"
assert_contains "$VERIFY" "A narrower command must still directly prove the claim being made." "verification keeps claim-proving floor"
assert_contains "$VERIFY" "A focused check supports only the correspondingly narrow claim; it never" "verification scopes focused evidence"
assert_contains "$VERIFY" "supports a broader completion claim." "verification forbids broad claims from narrow checks"
assert_contains "$VERIFY" "Run every claim-proving command as a standalone tool call so its result" "verification preserves raw command status"
assert_contains "$VERIFY" "exposes the actual exit status." "verification requires observable exit status"
assert_contains "$VERIFY" 'Appending status-printing or masking syntax such as `; echo`, `|| true`,' "verification names invalid masked evidence"
assert_contains "$VERIFY" "pipelines, or fallback commands invalidates that evidence; rerun the command" "verification rejects masked command results"
assert_contains "$VERIFY" 'Run `git diff` as a standalone command and inspect its result.' "verification requires observable diff"
assert_contains "$VERIFY" "Execute the mode-appropriate command fresh and completely" "verification gate requires fresh mode-appropriate command"
assert_contains "$VERIFY" "READ: Full output, check exit code, count failures" "verification still requires output and exit-status inspection"
assert_contains "$VERIFY" "Relying on a partial check that does not directly prove the stated claim" "verification red flag rejects irrelevant partial checks"
assert_contains "$VERIFY" "Expanding a narrow check into a broader completion claim" "verification red flag rejects claim expansion"
assert_contains "$VERIFY" '"Partial check is enough" | Only when it directly proves the correspondingly narrow claim;' "verification rationalization allows claim-matched focus"
assert_contains "$VERIFY" "it never proves a broader claim." "verification rationalization forbids broad extrapolation"
assert_not_matches "$VERIFY" 'Relying on partial verification|Partial proves nothing' "verification removes absolute partial-check warnings"
finish
